const me = [
  {
    accomodation_element: "0.00",
    basic_salary: "0.00",
    bonus_income: "0.00",
    cash_allowances: "0.00",
    chargeable_income: "0.00",
    deductible_reliefs: "0.00",
    excess_bonus: "0.00",
    final_tax_on_bonus: "0.00",
    name_of_employee: "asd Kwesi asd",
    non_cash_benefit: "0.00",
    non_resident: false,
    overtime_income: "0.00",
    overtime_tax: "0.00",
    position: "Cleaner",
    remarks: "sadfas",
    secondary_employment: false,
    serial_no: 44,
    severance_pay_paid: "0.00",
    social_security_fund: "0.00",
    tax_deductible: "0.00",
    third_tier: "0.00",
    tin: "asd23",
    total_assessable_income: "0.00",
    total_cash_emolument: "0.00",
    total_reliefs: "0.00",
    total_tax_payable_to_gra: "0.00",
    vehicle_element: "0.00",
  },
  {
    accomodation_element: "0.00",
    basic_salary: "0.00",
    bonus_income: "0.00",
    cash_allowances: "0.00",
    chargeable_income: "0.00",
    deductible_reliefs: "0.00",
    excess_bonus: "0.00",
    final_tax_on_bonus: "0.00",
    name_of_employee: "me asd me",
    non_cash_benefit: "0.00",
    non_resident: false,
    overtime_income: "0.00",
    overtime_tax: "0.00",
    position: "Cleaner",
    remarks: "asdas",
    secondary_employment: false,
    serial_no: 43,
    severance_pay_paid: "0.00",
    social_security_fund: "0.00",
    tax_deductible: "0.00",
    third_tier: "0.00",
    tin: "asdf223",
    total_assessable_income: "0.00",
    total_cash_emolument: "0.00",
    total_reliefs: "0.00",
    total_tax_payable_to_gra: "0.00",
    vehicle_element: "0.00",
  },
];
